// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFavoriteMotorbike.Infrastructure.Data;

#nullable disable

namespace MyFavoriteMotobike.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MyFavoriteMotobike.Infrastructure.Data.Entities.Administrator", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("UserId");

                    b.ToTable("Administrator");

                    b.HasData(
                        new
                        {
                            UserId = "81693837-9353-4dac-a5f2-4eade35a30f9",
                            Id = 1,
                            PhoneNumber = "+359877777777"
                        });
                });

            modelBuilder.Entity("MyFavoriteMotobike.Infrastructure.Data.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CountryOfOriginId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CountryOfOriginId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kawasaki"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Yamaha"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Suzuki"
                        },
                        new
                        {
                            Id = 5,
                            Name = "KTM"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Beta"
                        },
                        new
                        {
                            Id = 7,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Triumph"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Husaberg"
                        });
                });

            modelBuilder.Entity("MyFavoriteMotobike.Infrastructure.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Motocross"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dirt Bike"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sport Bike"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Touring"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Custom"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Street Fighter"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dual Sport"
                        });
                });

            modelBuilder.Entity("MyFavoriteMotobike.Infrastructure.Data.Entities.CountryOfOrigin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("CountriesOfOrigin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Great Britain"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sweden"
                        });
                });

            modelBuilder.Entity("MyFavoriteMotobike.Infrastructure.Data.Entities.Engine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CoolingType")
                        .HasColumnType("int");

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfStrokes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Engines");
                });

            modelBuilder.Entity("MyFavoriteMotobike.Infrastructure.Data.Entities.Motorbike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CubicCentimeters")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EngineId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("money");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EngineId");

                    b.HasIndex("UserId");

                    b.ToTable("Motorbikes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            CubicCentimeters = 250.00m,
                            Description = "This bike is for racing and amateur riding on a motocross track!",
                            ImageUrl = "https://content2.kawasaki.com/ContentStorage/KMC/ProductTrimGroup/56/1c0de86b-e024-4e09-8ba6-bd08b77344e5.jpg?w=750",
                            Model = "KX",
                            PricePerDay = 100.00m
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            CategoryId = 2,
                            CubicCentimeters = 450.00m,
                            Description = "This bike is for riding through mountains and off-road terrain!",
                            ImageUrl = "https://www.motofichas.com/images/cache/honda-crf450x-2011-739-a.jpg",
                            Model = "CRF",
                            PricePerDay = 100.00m
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 4,
                            CategoryId = 3,
                            CubicCentimeters = 1300.00m,
                            Description = "This bike is for riding on the road and it's one of the fastest bikes ever!",
                            ImageUrl = "https://dizzyriders.bg/uploads/thumbs/gallery/2021-02/fe6c02c5a7fe382814b184f1c9e0bb62-620x427.jpg",
                            Model = "Hayabusa",
                            PricePerDay = 200.00m
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 7,
                            CategoryId = 4,
                            CubicCentimeters = 1250.00m,
                            Description = "This bike is for long and comfortable riding on the road!",
                            ImageUrl = "https://dizzyriders.bg/uploads/thumbs/gallery/2021-02/fe6c02c5a7fe382814b184f1c9e0bb62-620x427.jpg",
                            Model = "R1250RT",
                            PricePerDay = 200.00m
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 8,
                            CategoryId = 5,
                            CubicCentimeters = 900.00m,
                            Description = "This bike is for easy riding on the road!",
                            ImageUrl = "https://imgd.aeplcdn.com/1280x720/bw/models/triumph-street-twin-2021-standard20210401131021.jpg?q=80",
                            Model = "Street Twin",
                            PricePerDay = 100.00m
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 3,
                            CategoryId = 6,
                            CubicCentimeters = 155.00m,
                            Description = "This bike is for riding on the road mostly in the city!",
                            ImageUrl = "https://www.indiacarnews.com/wp-content/uploads/2019/03/Yamaha-MT-15-International.jpg",
                            Model = "MT-15",
                            PricePerDay = 100.00m
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 5,
                            CategoryId = 7,
                            CubicCentimeters = 990.00m,
                            Description = "This adventure is for almost any terreain!",
                            ImageUrl = "https://mcn-images.bauersecure.com/wp-images/19502/951x634/990_adventure_dakar.jpg?mode=max&quality=90&scale=down",
                            Model = "Adventure",
                            PricePerDay = 100.00m
                        });
                });

            modelBuilder.Entity("MyFavoriteMotobike.Infrastructure.Data.Entities.UserMotorbikes", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MotorbikeId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "MotorbikeId");

                    b.HasIndex("MotorbikeId");

                    b.ToTable("UsersMotorbikes");
                });

            modelBuilder.Entity("MyFavoriteMotobike.Infrastructure.Data.Entities.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = "81693837-9353-4dac-a5f2-4eade35a30f9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "27b38051-36a8-4a52-a62b-e142776b37ea",
                            Email = "administrator@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "administrator@mail.com",
                            NormalizedUserName = "administrator@mail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEH0hJB1lI0Y1UXJwR1o9jc1HlMW6+snB44arY/9D4VO3rNT5Fmdh4w+dpq/fIVhfQw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "31aa8050-645d-44e0-a2c7-ba8c17e3b872",
                            TwoFactorEnabled = false,
                            UserName = "administrator@mail.com"
                        },
                        new
                        {
                            Id = "8700b0e1-1cc6-4e31-81d8-0dc734f1d679",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "af2f4339-47f2-46a7-a7d2-03e2025ae8d1",
                            Email = "guest@mail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "guest@mail.com",
                            NormalizedUserName = "guest@mail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEKNqsOgtVrVX+2KCcC5lK0kYm9meI2G+4gxcroLqG6XS1FoLYPZmWbYMFXv/aXiMog==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bbb1a6e9-0f3a-472a-9641-5b86f0a03af9",
                            TwoFactorEnabled = false,
                            UserName = "guest@mail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyFavoriteMotobike.Infrastructure.Data.Entities.Administrator", b =>
                {
                    b.HasOne("MyFavoriteMotobike.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFavoriteMotobike.Infrastructure.Data.Entities.Brand", b =>
                {
                    b.HasOne("MyFavoriteMotobike.Infrastructure.Data.Entities.CountryOfOrigin", null)
                        .WithMany("Brands")
                        .HasForeignKey("CountryOfOriginId");
                });

            modelBuilder.Entity("MyFavoriteMotobike.Infrastructure.Data.Entities.Motorbike", b =>
                {
                    b.HasOne("MyFavoriteMotobike.Infrastructure.Data.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFavoriteMotobike.Infrastructure.Data.Entities.Category", "Category")
                        .WithMany("Motorbikes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFavoriteMotobike.Infrastructure.Data.Entities.Engine", null)
                        .WithMany("Motorbikes")
                        .HasForeignKey("EngineId");

                    b.HasOne("MyFavoriteMotobike.Infrastructure.Data.Entities.User", null)
                        .WithMany("Motorbikes")
                        .HasForeignKey("UserId");

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyFavoriteMotobike.Infrastructure.Data.Entities.UserMotorbikes", b =>
                {
                    b.HasOne("MyFavoriteMotobike.Infrastructure.Data.Entities.Motorbike", "Motorbike")
                        .WithMany()
                        .HasForeignKey("MotorbikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFavoriteMotobike.Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motorbike");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFavoriteMotobike.Infrastructure.Data.Entities.Category", b =>
                {
                    b.Navigation("Motorbikes");
                });

            modelBuilder.Entity("MyFavoriteMotobike.Infrastructure.Data.Entities.CountryOfOrigin", b =>
                {
                    b.Navigation("Brands");
                });

            modelBuilder.Entity("MyFavoriteMotobike.Infrastructure.Data.Entities.Engine", b =>
                {
                    b.Navigation("Motorbikes");
                });

            modelBuilder.Entity("MyFavoriteMotobike.Infrastructure.Data.Entities.User", b =>
                {
                    b.Navigation("Motorbikes");
                });
#pragma warning restore 612, 618
        }
    }
}
